### ISSUE TITLE
测试用例的数据转换

### ISSUE THREAD

**Issue by Naflim** [zrq-github/VisualStudioExtensions#1]
在刷题过程中，官方提供的测试用例更类似于json的格式。这使得我在日常刷题中还需要手动将用例转换为自己语言的数据结构。有时这是十分麻烦的问题。
 想要一个能够复制官方测试用例粘贴在本地时,会根据当前文件格式自动粘贴为指定语言数据结构的功能。

**Comment by zrongqing** [comment]
OK
